package com.klist.chatbot.infrastructure.tourapi.mapper;

public enum TourApiMappingIssueCode {
    MISSING_REQUIRED_CONTENT_ID,
    MISSING_REQUIRED_CONTENT_TYPE_ID,
    MISSING_REQUIRED_NAME,
    MISSING_REQUIRED_SOURCE_MODIFIED_AT,
    INVALID_CONTENT_ID,
    INVALID_CONTENT_TYPE_ID,
    INVALID_COORDINATE,
    INVALID_DATE_TIME,
    UNSUPPORTED_CONTENT_TYPE_ID,
    OPTIONAL_FIELD_MISSING
}
