CREATE TABLE category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content_type_id INTEGER NOT NULL,
    large_category_code VARCHAR(20) NOT NULL,
    middle_category_code VARCHAR(20) NOT NULL,
    small_category_code VARCHAR(20) NOT NULL,
    category_name VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT uk_category_content_type_small_code
        UNIQUE (content_type_id, small_category_code)
);

CREATE TABLE region (
    region_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    area_code VARCHAR(20) NOT NULL,
    sigungu_code VARCHAR(20),
    region_code VARCHAR(50) NOT NULL,
    region_name VARCHAR(100) NOT NULL,
    parent_region_code VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_region PRIMARY KEY (region_id),
    CONSTRAINT uk_region_code UNIQUE (region_code)
);

CREATE TABLE tourist_spot (
    tourist_spot_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tour_api_content_id BIGINT NOT NULL,
    content_type_id INTEGER NOT NULL,
    category_id BIGINT,
    region_id BIGINT,
    large_category_code VARCHAR(20),
    middle_category_code VARCHAR(20),
    small_category_code VARCHAR(20),
    area_code VARCHAR(20),
    sigungu_code VARCHAR(20),
    legal_dong_region_code VARCHAR(20),
    legal_dong_sigungu_code VARCHAR(20),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    address VARCHAR(500),
    detail_address VARCHAR(500),
    zip_code VARCHAR(20),
    latitude NUMERIC(13, 10),
    longitude NUMERIC(13, 10),
    tel VARCHAR(100),
    opening_hours TEXT,
    admission_fee TEXT,
    official_url VARCHAR(2048),
    reservation_url VARCHAR(2048),
    image_url VARCHAR(2048),
    thumbnail_image_url VARCHAR(2048),
    source_created_at TIMESTAMP,
    source_modified_at TIMESTAMP NOT NULL,
    last_synced_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_tourist_spot PRIMARY KEY (tourist_spot_id),
    CONSTRAINT uk_tourist_spot_tour_api_content_id UNIQUE (tour_api_content_id),
    CONSTRAINT fk_tourist_spot_category
        FOREIGN KEY (category_id) REFERENCES category (category_id),
    CONSTRAINT fk_tourist_spot_region
        FOREIGN KEY (region_id) REFERENCES region (region_id)
);

CREATE TABLE chat_history (
    chat_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id VARCHAR(100),
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_chat_history PRIMARY KEY (chat_history_id)
);

CREATE INDEX idx_region_parent_region_code
    ON region (parent_region_code);

CREATE INDEX idx_tourist_spot_content_type_id
    ON tourist_spot (content_type_id);

CREATE INDEX idx_tourist_spot_category_id
    ON tourist_spot (category_id);

CREATE INDEX idx_tourist_spot_region_id
    ON tourist_spot (region_id);

CREATE INDEX idx_tourist_spot_source_modified_at
    ON tourist_spot (source_modified_at);

CREATE INDEX idx_chat_history_session_created_at
    ON chat_history (session_id, created_at);
